### PR TITLE
Add `cache-hit` outputs

### LINKED ISSUE #295: Set `cache-hit-...` output
`actions/cache` does set the output `cache-hit` if the cache was hit. Have a look at the docs: https://github.com/actions/cache#skipping-steps-based-on-cache-hit

Can we have the same here?
Looking at the implementation of `actions/cache` that shouldn't be too hard:
* https://github.com/actions/cache/blob/8f1e2e02865c42348f9baddbbaafb1841dce610a/src/restore.ts#L52
* https://github.com/actions/cache/blob/8f1e2e02865c42348f9baddbbaafb1841dce610a/src/utils/actionUtils.ts#L26-L28
* https://github.com/actions/cache/blob/8f1e2e02865c42348f9baddbbaafb1841dce610a/src/constants.ts#L8-L10

We would need an output for each cache however:
* `cache-hit-coursier`
* `cache-hit-sbt-ivy2-cache`
* `cache-hit-mill`
* `cache-hit-ammonite`

Based on the referenced example, we could for example:
```yml
...
    if: steps.cache.outputs.cache-hit-coursier != 'true'
...
```

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #295

Actually the fix is very very simple.

What do you think?

### CODE REVIEW

**Comment by mkurz** [comment]
@alexarchambault any chance you can have a look at this, ... maybe today? Thanks!

**Comment by mkurz** [comment]
@alexarchambault Merging this pull request will be very useful to us: https://github.com/playframework/playframework/pull/11142/files#diff-063ca77e012f959eba648db60e6868875fd1e70e5f5ac081193d848f8d61ef32R41
Thanks!

**Comment by mkurz** [comment]
@alexarchambault Any chance you can have a look? Thanks!

**Review by alexarchambault — APPROVED** [review]
Thanks!

**Comment by mkurz** [comment]
Thank you!

**Pull request merged**
